
# copy the files to ec2
- name: "copy file to ec2"
  copy:
    src: "artifact.tar.gz"
    dest: "~/"

# extract the files 
- name: Extract artifact.tar.gz web
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "Start PM2 SERVER"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start


   