
# copy the files to ec2
- name: "copy file to ec2"
  copy:
    src: "artifact.tar.gz"
    dest: "~/"

# extract the files 
- name: Extract artifact.tar.gz web
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "Install Dependance"
  become: true
  apt:
    name: ['nodejs',"npm"]
    state: latest
    update_cache: yes
    
- name: "Install PM2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Start PM2 SERVER"
  shell: |
    npm install
    pm2 stop default
    pm2 start index.js
    pm2 ls


   