- name: "Update Prometheus Target"
  become: true
  replace:
    path: /etc/prometheus/prometheus.yml
    after: "node_exporter"
    regexp: ^(.*)- targets:(.*)$
    replace: "      - targets: [{{ newBackendUrl }}]"

- name: "Show the content of the config file "
  become: true
  shell: cat /etc/prometheus/prometheus.yml
    

- name: "Restart prometheus Service"
  become: true
  systemd:
     state: restarted
     daemon_reload: yes
     name: prometheus